#!/usr/bin/env node
const fs = require('fs');
const { parseVisitor } = require('./');

const argv = process.argv.slice(2);

function readFile(filename) {
  return fs.readFileSync(filename === '-' ? 0 : filename, 'utf-8');
}

for (const arg of argv.length > 0 ? argv : ['-']) {
  parseVisitor(readFile(arg), str => console.log(str));
}
